# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/RM6785/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/realme/RM6785

PRODUCT_COPY_FILES += \
    vendor/realme/RM6785/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-mediatek.rc \
    vendor/realme/RM6785/proprietary/vendor/etc/init/init.bt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bt_drv.rc

PRODUCT_PACKAGES += \
    libaptXHD_encoder \
    libaptX_encoder \
    android.hardware.bluetooth@1.0-impl-mediatek \
    vendor.mediatek.hardware.bluetooth.audio@2.1-impl \
    libbluetooth_audio_session_mediatek \
    libbluetooth_hw_test \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbluetooth_relayer \
    libbluetoothem_mtk \
    libbt-vendor \
    vendor.mediatek.hardware.bluetooth.audio@2.1 \
    autobt \
    android.hardware.bluetooth@1.0-service-mediatek
